#!/bin/sh

resolve_navi_bookmarks() {
    echo "= window label \"Bookmarks\""
    echo "+ header label \"Bookmarks\""

    if [ -f ~/.navi_bookmarks ]
    then
        cat ~/.navi_bookmarks | while read line
        do
            label=$(echo $line | cut -d ',' -f 1 | tr -d '"')
            link=$(echo $line | cut -d ',' -f 2 | tr -d '"')

            echo "+ anchor label \"$label\" onclick \"get\" \"$link\""
        done
    else
        echo "+ text label \"No bookmarks found.\""
    fi
    exit 0
}

resolve_navi_history() {
    echo "= window label \"History\""
    echo "+ header label \"History\""

    if [ -f ~/.navi_history ]
    then
        cat ~/.navi_history | while read line
        do
            label=$(echo $line | cut -d ',' -f 1 | tr -d '"')
            link=$(echo $line | cut -d ',' -f 2 | tr -d '"')

            echo "+ anchor label \"$label\" onclick \"get\" \"$link\""
        done
    else
        echo "+ text label \"No history found.\""
    fi
    exit 0
}

resolve_navi() {
    case "$1" in
    navi://bookmarks)
        resolve_navi_bookmarks $@
        ;;
    navi://history)
        resolve_navi_history $@
        ;;
    esac
}

resolve_file() {
    path=${1#file://}

    if test -z $path
    then
        path=$(pwd)
    fi

    if test -f $path
    then
        cat $path
        exit 0
    elif test -d $path
    then
        echo "= window label \"Index of $path\""
        echo "+ header label \"Index of $path\""
        echo "+ divider"
        echo "+ table id table1 grid \"06:02:04\""
        echo "+ header2 in table1 label \"Name\""
        echo "+ header2 in table1 label \"Size\""
        echo "+ header2 in table1 label \"Modified\""

        find $path -mindepth 1 -maxdepth 1 -type d | while read entry
        do
            name=$(stat --printf="%n" "$entry")
            name=$(basename "$name")
            size=$(stat --printf="%s" "$entry")
            size=$(numfmt --to=si $size)
            modified=$(stat --printf="%Y" "$entry")
            modified=$(date -d @$modified)

            echo "+ anchor in table1 label \"$name/\" onclick \"get\" \"file://$entry\""
            echo "+ text in table1 label \"$size\""
            echo "+ text in table1 label \"$modified\""
        done

        find $path -mindepth 1 -maxdepth 1 -type f | while read entry
        do
            name=$(stat --printf="%n" "$entry")
            name=$(basename "$name")
            size=$(stat --printf="%s" "$entry")
            size=$(numfmt --to=si $size)
            modified=$(stat --printf="%Y" "$entry")
            modified=$(date -d @$modified)

            case "$name" in
            *.alfi)
                echo "+ anchor in table1 label \"$name\" onclick \"get\" \"file://$entry\""
                ;;
            *)
                echo "+ text in table1 label \"$name\""
                ;;
            esac

            echo "+ text in table1 label \"$size\""
            echo "+ text in table1 label \"$modified\""
        done

        exit 0
    fi

    exit 1
}

resolve() {
    case "$1" in
    navi://*)
        resolve_navi $@
        ;;
    file://*)
        resolve_file $@
        ;;
    esac
}

if [ $# -ge 1 ]
then
    resolve $@
fi

