struct alfi_widget *pool_prev(struct alfi_widget *widget);
struct alfi_widget *pool_next(struct alfi_widget *widget);
struct alfi_widget *pool_findbyname(char *name);
struct alfi_widget *pool_nextchild(struct alfi_widget *widget, struct alfi_widget *parent);
struct alfi_widget *pool_prevflag(struct alfi_widget *widget, unsigned int flag);
struct alfi_widget *pool_nextflag(struct alfi_widget *widget, unsigned int flag);
struct alfi_widget *pool_create(void);
void pool_destroy(struct alfi_widget *widget);
char *pool_allocate(char *string, unsigned int size, unsigned int count, char *content);
void pool_setup(void);
