void render_loadfont(struct resource_font *resource, char *url);
void render_loadimage(struct resource_image *resource, char *url);
void render_unloadfont(struct resource_font *resource);
void render_unloadimage(struct resource_image *resource);
void render_reset(float w, float h);
void render_flush(void);
void render_create(void);
void render_destroy(void);
float render_textwidth(struct style *style, char *text);
float render_textheight(struct style *style, char *text);
void render_filltext(struct style *style, char *text);
void render_filltextinput(struct style *style, char *text, int offset, struct style_color *frame_color_focus);
void render_fillborder(struct style *border, float bordersize);
void render_fillbordergap(struct style *border, float bordersize, float x, float w);
void render_fillrect(struct style *style);
void render_fillrectgap(struct style *border, float x, float w);
void render_fillcircle(struct style *style);
void render_fillimage(struct style *style, int image);
void render_background(int w, int h, struct style_color *color);
